### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by ghost** [rcmcdonough/rcmcdonough.github.io#5]
https://github.com/rcmcdonough/rcmcdonough.github.io/blob/master/dasmoto/index.html#L18

You forgot to wrap the item description in `p` tags. The `span` should be inside of a paragraph.

That being said, nice job using a proper inline tag like `span` to write your price information and giving each `span` tag the same class, "cost", which adequately describes the tag's content. 👍 

Using the same, but descriptive, class allows you to easily select all of the `span` tags related to pricing and will prevent bugs in the future.

**Comment by rcmcdonough** [comment]
@stevetoro thanks!  added **p** tags to each of the description sections.
